tasks:
  build:
    steps:
    - checkout
    - docker/build:
        image: sravanibikkina/my-rails-app11
        tags: ["${CI_COMMIT_SHA:0:8}", "latest", "${CI_REPO_BRANCH}"]


    steps:
    - checkout
    - cache/pull:
        key: bundle-{{ checksum "Gemfile.lock" }}

    - commands:
      - gem --version && ruby --version
      - gem install bundler:2.4.20
      - bundle --version

    - run: bundle install --path vendor/bundle || bundle check

    - cache/push:
        key: bundle-{{ checksum "Gemfile.lock" }}
        paths: [vendor/bundle]

    - reports/html: 
        dir: coverage
        index: index.html

    - run: docker logs sravanibikkina/my-rails-app11
      when: on_fail
