apiVersion: v1
kind: Service
metadata:
  name: my-ruby-app1-loadbalancer
spec:
  selector:
    app: my-ruby-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer

